name: CI Workflow 

on:
 # [push, pull_request]

jobs:
  lint:
   # runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install linters
        run: |
          pip install flake8 mypy

      - name: Run flake8 linter
        run: flake8 run.py roop

      - name: Run mypy static type checker
        run: mypy run.py roop

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo apt-get install -y python3-tk  # Install Tkinter
          pip3 install yt-dlp

     # - name: Download YouTube video
#        run: |
       #   wget -O ".github/examples/youtube.mp4" "https://px10.genyoutube.online/mates/en/download?url=ZTREjvNyOeQ%2BrM2CUnF6Z9q8OyNSR0xs/bwe6C4sTJ4px0miEEYnhr8tdrgRQI%2B0lfBa2nL1ukcEYl9DOQ0XrUWHoTxVahkLQmfsM2UML5A09rTokCUhXWEJfBMErQiv2gF18gcZq/hO5coScFHLB%2BUCg51tkVxrp8v6l4iFdFAKEkH1wOWTL0MuUdMzxDtOCzsbkBpipkuZagIKgzal4A%3D%3D"

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install Python dependencies
        run: pip install -r requirements-headless.txt

      - name: Run Python script
        run: |
          python run.py -s ".github/examples/runningmaneh.png" -t ".github/examples/5120418-hd_1080_1920_25fps.mp4" -o ".github/examples/output.mp4" --keep-frames --keep-fps --temp-frame-quality 1 --output-video-quality 1 --execution-provider cpu --execution-threads 1 --frame-processor face_swapper


      # Uncomment the following if you want to compare videos using PSNR
      # - name: Compare videos using PSNR (Optional)
      #   run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -

      # Uncomment the following if you want to scale the output to HD
      # - name: Convert output to HD
      #   run: |
      #     ffmpeg -i .github/examples/output.mp4 -vf "scale=1920:1080" -c:a copy .github/examples/output_hd.mp4

      - name: Upload processed video as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-video
          path: .github/examples/output.mp4
